name: Release Package to NPM

on:
  release:
    types: [created]

jobs:
  test-and-publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
